apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hedgedoc.fullname" . }}-config
  namespace: default
  labels:
    {{- include "hedgedoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
