{{- if not .Values.mumble.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mumble.fullname" . }}-auth
type: Opaque
stringData:
  user-password: {{ .Values.mumble.userPassword | quote }}
  admin-password: {{ .Values.mumble.adminPassword | quote }}
{{- end }}
