apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ctl-speak
      targetPort: ctl-speak
      protocol: TCP
      port: {{ .Values.service.port }}
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}
